properties([
    parameters([
        booleanParam(
            name: 'DESTROY',
            defaultValue: false,
            description: 'Check this to destroy Terraform infrastructure'
        )
    ])
])

pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('sec-key')
        AWS_SECRET_ACCESS_KEY = credentials('new-id')
        AWS_DEFAULT_REGION    = 'ap-northeast-1'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init & Apply') {
            when {
                expression { params.DESTROY == false }
            }
            steps {
                dir('AWS_All') {
                    sh 'terraform init'
                    sh 'terraform plan -out=tfplan'
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { params.DESTROY == true }
            }
            steps {
                dir('AWS_All') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Infrastructure provisioned or destroyed successfully!'
        }
        failure {
            echo '❌ Something went wrong. Check the logs.'
        }
    }
}
