pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('sec-key')   // Jenkins credential ID for AWS access key
        AWS_SECRET_ACCESS_KEY = credentials('new-id')   // Jenkins credential ID for AWS secret key
        AWS_DEFAULT_REGION    = 'ap-northeast-1'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init & Apply S3') {
            steps {
                dir('s3') {
                    sh 'terraform init'
                    sh 'terraform plan -out=tfplan'
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }

    post {
        success {
            echo 'S3 infrastructure provisioned successfully!'
        }
        failure {
            echo 'Something went wrong with S3. Check the logs.'
        }
    }
}
